#!/bin/sh
#

export PGDATA={{pkg.svc_data_path}}

{{#if svc.me.follower ~}}
cp {{pkg.svc_path}}/config/recovery.conf {{pkg.svc_data_path}}/
{{~/if}}

exec 2>&1
exec {{pkg.path}}/bin/postmaster \
     -c config_file={{pkg.svc_path}}/config/postgresql.conf
